-- Supabase migration: Create viewings table
CREATE TABLE IF NOT EXISTS viewings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  ref_no TEXT,
  city TEXT,
  viewing_date DATE,
  viewing_time TIME,
  client_name TEXT,
  client_mobile_no TEXT,
  result TEXT CHECK (result IN ('DEAL', 'NO DEAL', 'Negotiating', 'Scheduled')),
  comments TEXT,
  inform_teamleader BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for sorting by created_at
CREATE INDEX IF NOT EXISTS idx_viewings_created_at ON viewings(created_at DESC);

-- Index for user_id
CREATE INDEX IF NOT EXISTS idx_viewings_user_id ON viewings(user_id);

-- Enable Row Level Security
ALTER TABLE viewings ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only view their own viewings
CREATE POLICY "Users can view own viewings"
  ON viewings
  FOR SELECT
  USING (auth.uid()::text = user_id);

-- Policy: Users can only insert their own viewings
CREATE POLICY "Users can insert own viewings"
  ON viewings
  FOR INSERT
  WITH CHECK (auth.uid()::text = user_id);

-- Policy: Users can only update their own viewings
CREATE POLICY "Users can update own viewings"
  ON viewings
  FOR UPDATE
  USING (auth.uid()::text = user_id)
  WITH CHECK (auth.uid()::text = user_id);

-- Policy: Users can only delete their own viewings
CREATE POLICY "Users can delete own viewings"
  ON viewings
  FOR DELETE
  USING (auth.uid()::text = user_id);
