-- Supabase migration: Create clients table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  adding_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT,
  people TEXT,
  bedroom TEXT,
  cities TEXT,
  family_sharing TEXT,
  nationalities TEXT,
  jobs TEXT,
  pet TEXT,
  budget TEXT,
  move_in TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Index for sorting by created_at
CREATE INDEX IF NOT EXISTS idx_clients_created_at ON clients(created_at DESC);
